# Website settings
title: "Surya Avala"
description: "Surya Avala's personal website."
keywords: "Surya,Avala,personal,portfolio"
baseurl: ""
url: "https://suryaavala.com"
favicon: "static/img/favicon.ico"

author:
  name: 'Surya Avala'
  email: 'suryaavala.dev@gmail.com'
  github: 'https://github.com/suryaavala'
  linkedin: 'https://www.linkedin.com/in/suryaavala/'
  #TODO insta,twitter: 'https://www.twitter.com/suryaavala'
  head_img: 'static/img/landing/surya.png'
  tag: 'Machine Learning, Artificial Intelligence, Software, Computer Science, UNSW'
  desc: >
            <br /><strong>AI/Machine Learning Engineer</strong> with a background in Mechatronic Engineering and Software Development (enterprise & web).
            <br /><br />I have always been passionate about Computers and the ability to make them solve problems for us. I value encountering challenging situations, enjoy analyzing & solving problems and seeing the results. The work done by computers tend to have these characteristics in abundance. I am fascinated by that and want to solve as many problems as I can. Code is a by product of this phenomenon.
            <br /><br />Over time, I have acquired technical skills to code in Python, C, C++, Perl and few other languages. But again, I value the solving problems more than the tools used for that purpose.
            <br /><br />Strong believer in 👉🏾 <a target="_blank" href="https://medium.com/@Synced/artificial-intelligence-is-the-new-electricity-andrew-ng-cc132ea6264">"AI is the new Electricity"</a>.

stylesheets:
  - url: "lib/css/bootstrap.min.css"
  - url: "lib/css/animate.min.css"
  - url: "static/css/style.min.css"

scripts:
  - url: "lib/js/jquery.min.js"
  - url: "lib/js/wow.min.js"
  - url: "lib/js/pace.min.js"
  - url: "lib/js/bootstrap.min.js"

sections:
  - id: "about"
    name: "About"
    tpl: "about.html"
  - id: "career"
    name: "Career"
    tpl: "timeline.html"
  - id: "coding"
    name: "My Coding Activity"
    tpl: "coding.html"
  - id: "projects"
    name: "Projects"
    tpl: "projects.html"

# google analytics
ga:
  id: UA-87662337-1

# Build settings
encoding: "utf-8"
