# Website settings
title: "Surya Avala"
description: "Surya Avala's personal website."
keywords: "Surya,Avala,personal,portfolio"
baseurl: ""
url: "https://suryaavala.com"
favicon: "static/img/favicon.ico"

author:
  name: "Surya Avala"
  email: "suryaavala.dev@gmail.com"
  github: "https://github.com/suryaavala"
  linkedin: "https://www.linkedin.com/in/suryaavala/"
  #TODO insta,twitter: 'https://www.twitter.com/suryaavala'
  head_img: "static/img/landing/surya.png"
  tag: "Machine Learning, Artificial Intelligence, Software, Computer Science, UNSW, Engineer"
  desc: >
    <br /><a target=_blank href="https://medium.com/@tomaszdudek/but-what-is-this-machine-learning-engineer-actually-doing-18464d5c699"><strong>AI/Machine Learning Engineer</strong></a> who has worked on various aspects of Data Science/ML problems from brainstorming, prototyping, to productionizing and maintaining solutions, primarily specializing in chipping away the <a target=_blank href="https://www.google.com/search?q=hidden+technical+debt+in+machine+learning&oq=hidden+technical+debt+in+machine+learning+&aqs=chrome..69i57j0l4j69i60l3.10345j1j4&sourceid=chrome&ie=UTF-8">"Hidden Technical Debt in Machine Learning" </a>

    <br /><br /> A few buzzwords for the search engines (also some of my "skills"): <br />Machine Learning, Data Engineering, Data Analysis, Data Modelling, Algorithms, Classification, Regression, Supervised, Unsupervised, Deep Learning, Evaluation, Hyperparameter Tuning, Deployment/Productionizing, Monitoring/Maintenance, DevOps, MLOps, Distributed Computing, CI/CD, Testing, TDD
    <br /> Python, R, C, C++, Pandas, Numpy, Dask, Scikit Learn, Tensorflow, Keras, Flask, Django
    <br />Git, Bash, Docker, Kubernetes, Helm, Kops, Kubeflow, MLflow
    <br />AWS, GCP, Sagemaker, API Gateway, AI Platform, ML Engine, S3, Cloud Storage, EC2, VM, ECR, GCR

    <br /><br />A bit of a background on how I got into the field and why I am still here -> I have always been passionate about Computers and the ability to make them solve problems for us. I value encountering challenging situations, enjoy analyzing & solving problems and seeing the results. The work done by computers tend to have these characteristics in abundance. I am fascinated by that and want to solve as many problems as I can. Code is a by product of this phenomenon. 
    <br />Over time, I have acquired technical skills to code in a bunch of languages, tools. But again, I value the solving problems more than the tools used for that purpose.

    <br /><br />Strong believer in 👉🏾 <a target="_blank" href="https://youtu.be/fgbBtnCvcDI">"AI is the new Electricity"</a>.

stylesheets:
  - url: "lib/css/bootstrap.min.css"
  - url: "lib/css/animate.min.css"
  - url: "static/css/style.min.css"

scripts:
  - url: "lib/js/jquery.min.js"
  - url: "lib/js/wow.min.js"
  - url: "lib/js/pace.min.js"
  - url: "lib/js/bootstrap.min.js"

sections:
  - id: "about"
    name: "About"
    tpl: "about.html"
  - id: "career"
    name: "Career"
    tpl: "timeline.html"
  - id: "projects"
    name: "Projects"
    tpl: "projects.html"

# google analytics
ga:
  id: UA-87662337-1

# Build settings
encoding: "utf-8"
